version: '3'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "2222:2222" # 既に5432・2345番ポートが別プロジェクトで使われているため
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - EDITOR=vim
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 1192 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    ports:
      - 1192:1192 # 既に別プロジェクトで3000・3150番ポートが使われているため
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  gem_data:

